name: Assemble APK

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  apk:
    name: Generate Debug APK
    runs-on: [ ubuntu-latest ]
    steps:

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Create APK Debug
      - name: Build APK
        run: bash ./gradlew app:assembleDebug --stacktrace

      # Upload APK Debug
      - name: Upload APK Debug - ${{ env.date_today }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - Debug APK generated
          path: app/build/outputs/apk/debug/app-debug.apk
