# This is a basic workflow to help you get started with Actions

name: Unit Test CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run unit tests
  unit_tests:
    name: Unit Tests
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle

      - name: Unit data tests
        run: ./gradlew :data:testDebugUnitTest

      - name: Unit presentation tests
        run: ./gradlew :presentation:testDebugUnitTest
