# Workflow to run Unit Test on push, pull request and manually

name: Unit Test CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Run unit tests
  unit_tests:
    name: Unit Tests
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Run Data Unit Tests
      - name: Unit data tests
        run: ./gradlew :data:testDebugUnitTest

      # Run Domain Unit Tests
      - name: Unit domain tests
        run: ./gradlew :domain:testDebugUnitTest

      # Run Presentation Unit Tests
      - name: Unit presentation tests
        run: ./gradlew :presentation:testDebugUnitTest
